repos:
-   repo: local
    hooks:
    -   id: no-cyrillic-characters
        name: Check for Cyrillic characters
        entry: python tools/check_no_cyrillic.py
        language: python
        files: '\.(py|js|ts|cpp|cs|go|java|txt|md|feature)$'
        exclude: 'translations/.*'
