repos:
-   repo: local
    hooks:
    -   id: no-cyrillic-characters
        name: Check for Cyrillic characters
        entry: grep -nP '[а-яА-ЯіІїЇєЄґҐ]'
        language: system
        files: '\.(py|js|ts|cpp|cs|go|java|txt|md|feature)$'
        exclude: 'translations/.*'